---
- name: Update apt cache and install Pre-requisites
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - curl
    - apt-transport-https

- name: Install JRE
  package:
    name: "{{ riak_java_package }}"
    state: present
  when: riak_install_java and riak_java_package is defined

- name: Install JRE
  package:
    name: default-jre
    state: present
  when: riak_install_java and riak_java_package is undefined

- name: Check if Riak is installed
  stat:
    path: /etc/riak/riak.conf
  register: dist

- name: Add Package Cloud repository key without validation
  apt_key:
    url: "https://packagecloud.io/gpg.key"
    state: present
    validate_certs: no
  when:
    - not dist.stat.exists
    - riak_install_package_cloud

- name: Add Basho Riak repository (hosted at Package Cloud)
  apt_repository:
    repo: "{{ item }}"
    state="present"
  with_items:
    - "{{ riak_apt_repo_urls }}"
  when:
    - not dist.stat.exists
    - riak_install_package_cloud

- name: Install Riak for Debian
  package:
    name: "{{ riak_package }}"
    state: present
  when: not dist.stat.exists

- name: Set the riak ulimit for Debian
  copy:
    src: etc_security_limits.d_riak.conf
    dest: /etc/security/limits.d/riak.conf
  when: 'ansible_os_family == "Debian"'

- name: Set the riak ulimit for Ubuntu Trusty
  copy:
    src: etc_default_riak_ulimit
    dest: /etc/default/riak
    owner: riak
    group: riak
  when: ansible_distribution_release == "trusty" 

- name: Set the riak ulimit for Ubuntu Xenial
  lineinfile:
    dest: /lib/systemd/system/riak.service
    line: "LimitNOFILE=131072"
    insertafter: "^RuntimeDirectory=riak"
  when: ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie"

- name: Reload systemd
  systemd:
    name: riak
    enabled: yes
    state: restarted
    daemon_reload: yes
  when: '(ansible_distribution_release == "xenial" or ansible_distribution_release == "jessie") and (riak_init_system == "system")'
