---
- name: install riak
  apt: name={{ riak_package }} state=present
  when: riak_custom_package == False

- name: install riak custom
  command: dpkg --skip-same-version -i {{ riak_package }}
  register: dpkg_result
  changed_when: dpkg_result.stdout.startswith('Selecting')
  when: riak_custom_package != False

# Remove following correction of defect https://github.com/basho/riak/issues/561
- name: patch init.d script
  copy: src=etc_initd_riak dest=/etc/init.d/riak owner=root group=root mode=0755

- name: patch env.sh script
  copy: src=usr_lib_riak_lib_env.sh dest=/usr/lib/riak/lib/env.sh owner=riak group=riak mode=0644

- name: set the riak ulimit
  copy: src=etc_default_riak_ulimit dest=/etc/default/riak owner=riak group=riak
