---
- name: Include DEB vars
  include_vars: Debian.yml
  tags: Debian

- name: Install package cloud repo
  shell: "curl https://packagecloud.io/install/repositories/basho/riak/script.deb | sudo bash"
  tags: Debian

- name: Install Riak for Debian
  apt: name={{ riak_package }} state=present
  tags: Debian

- name: Set the riak ulimit for Debian
  copy: src=etc_default_riak_ulimit dest=/etc/default/riak owner=riak group=riak
  tags: Debian
