---
- name: Include RHEL vars
  include_vars: RedHat.yml
  tags: RedHat

- name: "Install Java & libselinux-python"
  yum: "name={{ item }} state=present"
  tags: RedHat
  with_items:
    - java-1.7.0-openjdk
    - libselinux-python

- name: Install package cloud repo
  shell: "curl https://packagecloud.io/install/repositories/basho/riak/script.rpm | sudo bash"
  tags: RedHat

- name: Install Riak for RedHat
  yum: "name={{ riak_package }} state=present"
  tags: RedHat
