---
- name: "Install Java & libselinux-python"
  package: "name={{ item }} state=present"
  tags: RedHat
  with_items:
    - libselinux-python

- name: Install JDK
  package: 'name={{ riak_java_package }} state=present update_cache=yes cache_valid_time=3600'
  tags: RedHat
  when: 'riak_install_java and riak_java_package is defined'

- name: Install JDK
  package: 'name=java-1.7.0-openjdk state=present update_cache=yes cache_valid_time=3600'
  tags: RedHat
  when: 'riak_install_java and riak_java_package is undefined'

- name: Check if Riak is installed
  stat: path=/etc/riak/riak.conf
  tags: RedHat
  register: dist

- name: Set up packagecloud install script
  tags: RedHat
  template: src=packagecloud_rpm.sh.j2 dest=/tmp/packagecloud_rpm.sh group=root mode=0755

- name: Install package cloud repo if Riak is not already installed
  command: '/tmp/packagecloud_rpm.sh'
  tags: RedHat
  when:
    - not dist.stat.exists

- name: Install Riak for RedHat
  package: "name={{ riak_package }} state=present"
  tags: RedHat
