---
- name: Run riak_disk_tune
  command:
    /bin/bash /usr/local/bin/riak_disk_tune.sh

- name: restart procps
  service:
    name: procps
    state: restarted

- name: Wait for http
  wait_for:
    port: "{{ riak_http_port }}"

- name: Wait for kv
  riak: 
    wait_for_service: kv
    http_conn: "{{ riak_http_bind_ip }}:{{ riak_http_port }}"

- name: Commit cluster change
  riak:
    command: commit
    http_conn: "{{ riak_http_bind_ip }}:{{ riak_http_port }}"

- name: Wait for handoffs
  riak:
    wait_for_handoffs: 1200
    http_conn: "{{ riak_http_bind_ip }}:{{ riak_http_port }}"

- name: Wait for ring
  riak: 
    wait_for_ring: 600
    http_conn: "{{ riak_http_bind_ip }}:{{ riak_http_port }}"
